### PR TITLE
Potential fix to the readString() function.

### PR DESCRIPTION
**Pull request by ghost**
I think it is a encoding issue. Let me know if this will not work.

### CODE REVIEW

**Comment by vijfhoek** [comment]
Oh, I think BinaryReader and BinaryWriter aren't compatible with Java... Darn it. Would've saved us so much work...

22:41:46 [SEVERE] java.io.IOException: Received string length longer than maximu
m allowed (13312 > 64)

**Comment by Sharparam** [comment]
Could that (BinaryRead/Writer) incompatibility be an issue about Java using different encoding by default?

**Comment by ghost** [comment]
I sent another pull request to fix this.

**Comment by vijfhoek** [comment]
@F16Gaming The difference is, that Java uses a 16bit integer for the string length, and the C# Binary{Writer,Reader} an 8bit integer, if I remember correctly.

**Pull request closed without merging**
